# We need to test :
# Client access to the repositories (for various targets)
# build-slave configuration
sudo: required

language: bash

env:
  - OSDIR=u1404
  - OSDIR=centos-6

services:
  - docker

before_install:
  - cd $OSDIR

install:
  - docker build -t ansiblecontainer
#  - docker run -d aaroc/code-rade-build-slave:u1404 /bin/sh -c "echo hi"
script:
  - docker run  ansiblecontainer /bin/sh -c echo hi

after_success:

after_failure:

notifications:
  slack:
    rooms:
      - africa-arabia-roc:qn956vBmV7VIyJ1Xod4Cmnd5#coderade
