# We need to test :
# Client access to the repositories (for various targets)
# build-slave configuration
sudo: required

language: bash

env:
  - OS=u1404
  - OS=u1604
  - OS=centos6
  - OS=centos7
# 
# matrix:
#   allow_failures:
#     - env: OS=centos7
services:
  - docker

before_install:
  - git clone --recursive https://github.com/AAROC/DevOps

# Build the container
install:
  - docker build -t quay.io/aaroc/ansible-ready-${OS} -f Dockerfile.$OS .
script:
  - docker run quay.io/aaroc/ansible-ready-${OS} ansible localhost -c local -m setup

after_success:
  - docker push quay.io/aaroc/ansible-ready-${OS}
after_failure:

notifications:
  slack:
    rooms:
      - africa-arabia-roc:qn956vBmV7VIyJ1Xod4Cmnd5#coderade
